{{- if not .Values.externalDatabase.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tc.v1.common.lib.chart.names.fullname" . }}-db
  labels:
    {{- include "tc.v1.common.lib.metadata.allLabels" $ | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.postgresql.enabled }}
  database-url: "postgres://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ include "tc.v1.common.lib.chart.names.fullname" . }}-postgresql:5432/{{ .Values.postgresql.auth.database }}"
  {{- else if .Values.externalDatabase.host }}
  database-url: "postgres://{{ .Values.externalDatabase.username }}:{{ .Values.externalDatabase.password }}@{{ .Values.externalDatabase.host }}:{{ .Values.externalDatabase.port }}/{{ .Values.externalDatabase.database }}"
  {{- end }}
{{- end }}

{{- if not .Values.externalRedis.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tc.v1.common.lib.chart.names.fullname" . }}-redis
  labels:
    {{- include "tc.v1.common.lib.metadata.allLabels" $ | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.redis.enabled }}
  {{- if .Values.redis.auth.enabled }}
  redis-url: "redis://:{{ .Values.redis.auth.password }}@{{ include "tc.v1.common.lib.chart.names.fullname" . }}-redis-master:6379"
  {{- else }}
  redis-url: "redis://{{ include "tc.v1.common.lib.chart.names.fullname" . }}-redis-master:6379"
  {{- end }}
  {{- else if .Values.externalRedis.host }}
  {{- if .Values.externalRedis.password }}
  redis-url: "redis://:{{ .Values.externalRedis.password }}@{{ .Values.externalRedis.host }}:{{ .Values.externalRedis.port }}"
  {{- else }}
  redis-url: "redis://{{ .Values.externalRedis.host }}:{{ .Values.externalRedis.port }}"
  {{- end }}
  {{- end }}
{{- end }}
