{{- if .Values.postgresql.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tc.v1.common.lib.chart.names.fullname" . }}-db
  labels:
    {{- include "tc.v1.common.lib.metadata.allLabels" $ | nindent 4 }}
type: Opaque
stringData:
  database-url: "postgres://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ include "tc.v1.common.lib.chart.names.fullname" . }}-postgresql:5432/{{ .Values.postgresql.auth.database }}"
{{- end }}

{{- if .Values.redis.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tc.v1.common.lib.chart.names.fullname" . }}-redis
  labels:
    {{- include "tc.v1.common.lib.metadata.allLabels" $ | nindent 4 }}
type: Opaque
stringData:
  redis-url: "redis://{{ include "tc.v1.common.lib.chart.names.fullname" . }}-redis-master:6379"
{{- end }}
