{{- if not .Values.outline.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "getoutline.fullname" . }}
  labels:
    {{- include "getoutline.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.outline.secretKey }}
  secret-key: {{ .Values.outline.secretKey | b64enc | quote }}
  {{- else }}
  secret-key: {{ randAlphaNum 64 | b64enc | quote }}
  {{- end }}
  {{- if .Values.outline.utilsSecret }}
  utils-secret: {{ .Values.outline.utilsSecret | b64enc | quote }}
  {{- else }}
  utils-secret: {{ randAlphaNum 64 | b64enc | quote }}
  {{- end }}
  {{- if and .Values.outline.oidc.enabled (not .Values.outline.oidc.existingSecret) }}
  oidc-client-id: {{ .Values.outline.oidc.clientId | b64enc | quote }}
  oidc-client-secret: {{ .Values.outline.oidc.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if and .Values.outline.slack.enabled (not .Values.outline.slack.existingSecret) }}
  slack-client-id: {{ .Values.outline.slack.clientId | b64enc | quote }}
  slack-client-secret: {{ .Values.outline.slack.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if and .Values.outline.google.enabled (not .Values.outline.google.existingSecret) }}
  google-client-id: {{ .Values.outline.google.clientId | b64enc | quote }}
  google-client-secret: {{ .Values.outline.google.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if and .Values.outline.azure.enabled (not .Values.outline.azure.existingSecret) }}
  azure-client-id: {{ .Values.outline.azure.clientId | b64enc | quote }}
  azure-client-secret: {{ .Values.outline.azure.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if and .Values.outline.smtp.enabled (not .Values.outline.smtp.existingSecret) }}
  smtp-username: {{ .Values.outline.smtp.username | b64enc | quote }}
  smtp-password: {{ .Values.outline.smtp.password | b64enc | quote }}
  {{- end }}
  {{- if and (not .Values.postgresql.enabled) (not .Values.externalDatabase.existingSecret) }}
  database-password: {{ .Values.externalDatabase.password | b64enc | quote }}
  {{- end }}
{{- end }}
