annotations:
  artifacthub.io/links: |-
    - name: support
      url: https://cfi2017.github.io/helm-charts
  max_scale_version: 24.04.1
  min_scale_version: 24.04.0
  truecharts.org/category: media
  truecharts.org/max_helm_version: "3.17"
  truecharts.org/min_helm_version: "3.14"
  truecharts.org/train: stable
apiVersion: v2
appVersion: 6.13.3
dependencies:
  - name: common
    version: 28.17.1
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: cross-seed can be used to spread torrents across multiple indexers
home: https://www.cross-seed.org/
icon: https://www.cross-seed.org/img/cross-seed.svg
keywords:
  - cross-seed
  - torrrent
kubeVersion: '>=1.24.0-0'
maintainers:
  - name: cfi2017
    email: info@swiss.dev
    url: https://github.com/cfi2017
name: cross-seed
sources:
  - https://ghcr.io/cross-seed/cross-seed
  - https://github.com/cross-seed/cross-seed
type: application
version: 6.13.3
