annotations:
  artifacthub.io/links: |-
    - name: support
      url: https://cfi2017.github.io/helm-charts
  max_scale_version: 24.04.1
  min_scale_version: 24.04.0
  truecharts.org/category: productivity
  truecharts.org/max_helm_version: "3.17"
  truecharts.org/min_helm_version: "3.14"
  truecharts.org/train: stable
apiVersion: v2
appVersion: 1.0.0-2
dependencies:
  - name: common
    version: 28.17.1
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
  - name: redis
    version: "0.13.4"
    repository: oci://registry-1.docker.io/cloudpirates
    condition: redis.enabled
  - name: postgres
    alias: postgresql
    version: "0.11.5"
    repository: oci://registry-1.docker.io/cloudpirates
    condition: postgresql.enabled
deprecated: false
description: The fastest knowledge base for growing teams. Beautiful, realtime collaborative, feature packed, and markdown compatible.
home: https://www.getoutline.com/
icon: https://raw.githubusercontent.com/outline/outline/main/public/images/icon-192.png
keywords:
  - outline
  - wiki
  - knowledge-base
  - documentation
kubeVersion: '>=1.24.0-0'
maintainers:
  - name: cfi2017
    email: info@swiss.dev
    url: https://github.com/cfi2017
name: getoutline
sources:
  - https://hub.docker.com/r/outlinewiki/outline
  - https://github.com/outline/outline
type: application
version: 1.0.0
