annotations:
  artifacthub.io/links: |-
    - name: support
      url: https://cfi2017.github.io/helm-charts
apiVersion: v2
appVersion: 1.0.0-2
dependencies:
  - name: redis
    version: "0.13.4"
    repository: oci://registry-1.docker.io/cloudpirates
    condition: redis.enabled
  - name: postgres
    alias: postgresql
    version: "0.11.5"
    repository: oci://registry-1.docker.io/cloudpirates
    condition: postgresql.enabled
deprecated: false
description: The fastest knowledge base for growing teams. Beautiful, realtime collaborative, feature packed, and markdown compatible.
home: https://www.getoutline.com/
icon: https://raw.githubusercontent.com/outline/outline/main/public/images/icon-192.png
keywords:
  - outline
  - wiki
  - knowledge-base
  - documentation
kubeVersion: '>=1.24.0-0'
maintainers:
  - name: cfi2017
    email: info@swiss.dev
    url: https://github.com/cfi2017
name: getoutline
sources:
  - https://hub.docker.com/r/outlinewiki/outline
  - https://github.com/outline/outline
type: application
version: 1.0.1
